method: "Policy Gradient"
model: "FCNN"
device: "cpu"
input_dim: 3
hidden_dim: 128
batch_size: 40
num_users: 6
num_channels: 3
P_T: 12

metric: "MSR"
num_episodes: 4000
num_tests: 400
learning_rate: 1e-4
temp_episodes: 2
loss_threshold: 1
error_threshold: 2e-1
T: 1 # number of baseline model to successively success validation set
data_dir: simulations/

validate_every: 200
num_validations: 5
validation_seeds: [201910939, 201910931, 202015049, 201810972, 201911183]
# validation_seeds: [2024, 2025, 2026, 2027, 2028]
